### test
GET http://localhost:8000/api/test/
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0MDg0MTA2LCJpYXQiOjE3NDM5OTc3MDYsImp0aSI6IjFmYTk5OTFjZmZlODRiNzc4MDlhMDE3MmYyYWRjNzE0IiwidXNlcl9pZCI6IjgyOGVlZjI5LTcwZTMtNDZjNC04ZDgyLTFjMTQ5MmU1MGI3YiJ9.lBnXOuXYegY5EYYt9OluYYgx6Xx9BJEQpjEgWnK1Kqc


### register
POST http://localhost:8000/account/
Content-Type: application/json

{
    "email": "some_2@example.com",
    "password": "some123456"
}

### obtain
POST http://localhost:8000/api/account/
Content-Type: application/json

{
    "email": "some_2@example.com",
    "password": "some123456"
}


### player_jail_action
POST http://localhost:8000/actions/wallet/jail-action/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzNjAzMTk5LCJpYXQiOjE3NDM1OTU5OTksImp0aSI6IjAyZTNjZWY2MjUwNDRjNDQ5YTc5YTRiZWQ4M2I1ODBhIiwidXNlcl9pZCI6IjcxNTAxNWZmLWY5N2UtNDc4Ny1iMzVmLWZmOWI4MGJmZTg4MiIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6ImJhbmsifQ.ZZ1QD69siWqMS23KZ5fAcPqg94BDwJHqY_iTF832FCc

{
    "option": "roll_dice"
}

### create_room
POST http://localhost:8000/api/room/create-room/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0MDAyNzQxLCJpYXQiOjE3NDM5OTU1NDEsImp0aSI6IjcyM2EzZTgwMDY0NDQyYzhiMzZkNDlmYmQ0YjQxZmRhIiwidXNlcl9pZCI6IjgyOGVlZjI5LTcwZTMtNDZjNC04ZDgyLTFjMTQ5MmU1MGI3YiIsImVtYWlsIjoic29tZV8zQGV4YW1wbGUuY29tIiwidXNlcm5hbWUiOm51bGx9.QCTuWvRul3Dnc6lVk3YryhSN3GndAGCb3OXIsO0jVRY

{
    "name": "mygame"
}

### create_ticket
POST http://localhost:8000/api/room/create-ticket/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0MDg1MjY2LCJpYXQiOjE3NDM5OTg4NjYsImp0aSI6IjMxMTE2NTQxZWM4MTQzYjZhMzJmOWVkN2ZiMTNjZWExIiwidXNlcl9pZCI6IjI3OTk5MzVhLTVmZjAtNGEzMS04MWRjLTljOTM3MjFmYzRiNyJ9.4cAFVM7FjiRdJhXPbSZOT400nWocDG-2zquozO7B8mI

{
    "room": "309fbe31509d478da13d8f55b5a4a5b4"
}

### send_ticket
POST http://localhost:8000/api/room/send-ticket/a9ee152e-6626-49a4-b9e7-912bfca380cd/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzODMwMDYxLCJpYXQiOjE3NDM4MjI4NjEsImp0aSI6IjIxMzI5ZTNkNzc3MTQ3NDg5ZDM2OGZmOTYxYjVmMjFkIiwidXNlcl9pZCI6IjcxNTAxNWZmLWY5N2UtNDc4Ny1iMzVmLWZmOWI4MGJmZTg4MiIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6IndhbGxldF9iYW5rIn0.A_njJhVRujR5lXZ_xSWBkT9pPQIw-DrUtjK96qo2oBE

{
    "email": "farhangmalek1367@gmail.com"
}

### use_ticket
GET http://localhost:8000/api/room/use-ticket/11a550b6-e332-446e-8e87-a0425265042d/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0MDg2MjQ0LCJpYXQiOjE3NDM5OTk4NDQsImp0aSI6ImEwODQyOTFkNDE2MzQ2ZTE4ODUwMGU4N2Q4MDg4MjFhIiwidXNlcl9pZCI6Ijc2OTlhNGFlLWNiOTYtNDhmYi04ZTlkLWVmM2IxZjM4MzQ2MCJ9.Kp6gEDuznkJmzrQkJiDIMjmOymkALaTGpBcfJWNQkBg

# {
#     "email": "some_2@example.com",
#     "password": "some12345"
# }
