# Generated by Django 5.1.7 on 2025-04-04 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='invitee',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='inviter',
        ),
        migrations.AlterField(
            model_name='room',
            name='player',
            field=models.ManyToManyField(blank=True, related_name='player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='room',
        ),
        migrations.AddField(
            model_name='ticket',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='room.room'),
        ),
    ]
