# Generated by Django 5.2 on 2025-04-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='is_started',
            new_name='is_running',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_paused',
        ),
    ]
