# Generated by Django 5.1.7 on 2025-03-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='imprisoned',
            field=models.BooleanField(default=False),
        ),
    ]
