# Generated by Django 5.2 on 2025-04-10 11:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('position', models.IntegerField(default=0)),
                ('color', models.CharField(blank=True, choices=[('brown', 'Brown'), ('blue', 'Blue'), ('pink', 'Pink'), ('orange', 'Orange'), ('red', 'Red'), ('yellow', 'Yellow'), ('green', 'Green'), ('violet', 'Violet'), ('white', 'White')], max_length=6)),
                ('type', models.CharField(choices=[('residential', 'Residential'), ('station', 'Station'), ('utility', 'Utility'), ('public', 'Public')], max_length=11)),
                ('price', models.IntegerField(default=0)),
                ('rent_single', models.IntegerField(default=0)),
                ('rent_set', models.IntegerField(default=0)),
                ('rent_1', models.IntegerField(blank=True, default=0, null=True)),
                ('rent_2', models.IntegerField(blank=True, default=0, null=True)),
                ('rent_3', models.IntegerField(blank=True, default=0, null=True)),
                ('rent_4', models.IntegerField(blank=True, default=0, null=True)),
                ('rent_5', models.IntegerField(blank=True, default=0, null=True)),
                ('loan_amount', models.IntegerField(default=0)),
                ('loan_back_amount', models.IntegerField(default=0)),
                ('house_price', models.IntegerField(blank=True, default=0, null=True)),
                ('hotel_price', models.IntegerField(blank=True, default=0, null=True)),
                ('dwelling_counts', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
