# Generated by Django 5.1.7 on 2025-04-02 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='dwelling_status',
            field=models.CharField(choices=[('0_house', '0_house'), ('1_house', '1_house'), ('2_houses', '2_houses'), ('3_houses', '3_houses'), ('4_houses', '4_houses'), ('hotel', 'Hotel')], default='0_house', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
    ]
