# Generated by Django 5.2 on 2025-04-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='colSpan',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='colStart',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='rowSpan',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='rowStart',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
