# Generated by Django 5.1.7 on 2025-04-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_dwelling_status_alter_property_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='dwelling_status',
        ),
        migrations.AddField(
            model_name='property',
            name='dwelling_counts',
            field=models.IntegerField(default=0),
        ),
    ]
