# Generated by Django 5.2 on 2025-04-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_rename_colspan_property_h_rename_colstart_property_w_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='r',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
