# Generated by Django 5.2 on 2025-04-16 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_property_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='h',
            new_name='colSpan',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='r',
            new_name='colStart',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='w',
            new_name='rotation',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='x',
            new_name='rowSpan',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='y',
            new_name='rowStart',
        ),
    ]
