# Generated by Django 5.2 on 2025-04-22 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_rename_h_property_colspan_rename_r_property_colstart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='colSpan',
        ),
        migrations.RemoveField(
            model_name='property',
            name='colStart',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rotation',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rowSpan',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rowStart',
        ),
    ]
