# Generated by Django 5.2 on 2025-04-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_remove_property_colspan_remove_property_colstart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='orientation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
