# Generated by Django 5.2 on 2025-04-25 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_property_orientation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='orientation',
        ),
    ]
